export const COOKIE_SHOP_REDIRECT_KEY = 'shop-redirect'
export const COOKIE_AUTH_BEFORE_REDIRECT_LOCATION_KEY = 'login-location'
export const COOKIE_OLD_CATALOG_TS_USER_KEY = 'ts-user'
export const COOKIE_STORAGE_KEY = 'user'
export const COOKIE_TS_USER_CONTRAGENT = 'ts-user-contragent'
export const COOKIE_SELECTED_CONTRAGENT = 'selected-contragent'
